# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict # in case somebody is using Windows
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
        exclude: .vscode/ # vscode .json files have comments
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: forbid-submodules
    -   id: no-commit-to-branch
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/python-poetry/poetry
    rev: '1.3.2'
    hooks:
      - id: poetry-check
      - id: poetry-lock
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
-   repo: local
    # must use the local version of pylint, so it can scan our dependencies
    hooks:
    -   id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args:
            [
              "-rn", # Only display messages
              "-sn", # Don't display the score
            ]
- repo: https://github.com/pycqa/isort
  rev: 5.11.4
  hooks:
    - id: isort
      name: isort (python)
