# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict # in case somebody is using Windows
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
        exclude: .vscode/|.devcontainer/ # vscode/devcontainer .json files have comments
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: forbid-submodules
    -   id: no-commit-to-branch
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/pdm-project/pdm
    rev: '2.8.0'
    hooks:
      - id: pdm-lock-check
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
-   repo: local
    # must use the local version of pylint, so it can scan our dependencies
    hooks:
    -   id: pylint
        name: pylint
        entry: pdm run pylint
        language: system
        types: [python]
        args:
            [
              "-rn", # Only display messages
              "-sn", # Don't display the score
              "--extension-pkg-whitelist=nqm.irimager", # import our custom C extension
            ]
    -   id: mypy
        name: mypy
        entry: pdm run mypy
        language: system
        types: [python]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v16.0.6'
  hooks:
    - id: clang-format
      types: ["c++"]
