[tool.poetry]
name = "nqm.irimager"
# poetry will convert SemVer to a PEP 440 compliant version string
# but we should use PEP 440 directly instead
version = "0.1.0a0" # equivalent to 0.1.0-alpha.0
description = "Python module for interfacing with EvoCortex IRImagerDirect SDK"
authors = ["Alois Klink <alois@nquiringminds.com>"]
license = "UNLICENSED"
readme = "README.md"
packages = [{include = "nqm", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.21.0"
pylint = "^2.15.10"
mypy = "^0.991"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint."messages control"]
# isort sorts our imports for us and we occasionally get conflicts
disable = ["wrong-import-position"]

[tool.pylint.format]
# for compatibility with black
max-line-length = "88"

[tool.isort]
profile = "black"

[tool.mypy]
# required since we store our data in a src/ subdir
explicit_package_bases = true
mypy_path = "src"
