name: Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Install pdm
        run: pipx install pdm
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: 'pdm.lock'
      - run: pdm install
      - name: Run pre-commit checks
        env:
          # SKIP `no-commit-to-branch`, otherwise CI on `main` will fail,
          # see https://github.com/pre-commit/pre-commit-hooks/issues/265
          SKIP: "no-commit-to-branch"
        run: pdm run pre-commit run --show-diff-on-failure --color=always
      - name: Check whether nqm.irimager stubs match implementation
        env:
          MYPYPATH: src
        run: |
          stubtest_output="$(pdm run stubtest nqm.irimager || true)"
          if echo $stubtest_output \
            | grep '^error' \
            | grep --invert-match 'error: nqm.irimager.IRImager is inconsistent, metaclass differs'; then

            echo "::error ::Stubtest returned unexpected errors, ${stubtest_output}"
            exit 1
          else
            # no unexpected errors
            exit 0
          fi
      - name: Test with pytest
        run: pdm run pytest
